

const data = {

  products: [
    {
      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Outfits',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Outfits',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Outfits',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Outfits',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'KENT',
      slug: 'kent',
      category: 'Electronics',
      image: '/images/kent.png',
      price: 65,
      countInStock: 5,
      brand: 'kent ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'IFB',
      slug: 'ifb',
      category: 'Electronics',
      image: '/images/IFB.png',
      price: 65,
      countInStock: 5,
      brand: 'IFB ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'VGR TRIMMER',
      slug: 'vgr',
      category: 'Electronics',
      image: '/images/VGR.png',
      price: 65,
      countInStock: 5,
      brand: 'VGR ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Kent Grand',
      slug: 'kent grand',
      category: 'Electronics',
      image: '/images/kentG.png',
      price: 65,
      countInStock: 5,
      brand: 'KENT ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'SAFARI',
      slug: 'safari',
      category: 'Outfits',
      image: '/images/Sbag.png',
      price: 65,
      countInStock: 5,
      brand: 'Safari brand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'ASIAN',
      slug: 'asian',
      category: 'Sport',
      image: '/images/Furo.png',
      price: 65,
      countInStock: 5,
      brand: 'ASIAN',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '11',
      name: 'BUTTERFLY',
      slug: 'butterfly',
      category: 'Electronics',
      image: '/images/Btf.png',
      price: 65,
      countInStock: 5,
      brand: 'butterfly ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '12',
      name: 'American Tourister Bag',
      slug: 'a bag',
      category: 'Outfits',
      image: '/images/abag.png',
      price: 65,
      countInStock: 5,
      brand: 'AMERICAN TOURISTER ',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },


  ],
};
export default data;